on: [push]

jobs:
  setup-tf-workspace:
    name: Setup Terraform workspace
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup workspace
        uses: cbsinteractive/create-tfc-workspace-action@v3
        with:
          organization: hashicorp-shauncoss
          workspace: "my-workspace-name"
          token: e20zrXF4ytNRUQ.atlasv1.QpC06hEXYyo8O2gU3xcT9Ao6IYSEPWP4yeBEWwb36qSDyNJsJWKTDxPRlJr1wbz4NxM
